### PR TITLE
Flatpak preparation and manifest

### PR DESCRIPTION
**Pull request by cosimoc**
https://phabricator.endlessm.com/T17177

### CODE REVIEW

**Comment by cosimoc** [comment]
Thanks for the review @ptomato. I think I addressed all of your points.

I decided to keep the separate JSON files for the python dependencies; those need to installed in that specific order, and just trying to install all of them at the same time with `pip3` won't work.

**Comment by ptomato** [comment]
Another thing I've noticed while working on upgrading the Facebook API calls is that posting photos doesn't work on this branch:
```
Traceback (most recent call last):
  File "/app/share/eos-photos/src/share/facebook_post.py", line 36, in post_image
    self._graph_api.put_photo(open(file_name), message=message)
  File "/app/share/eos-photos/src/share/facebook.py", line 210, in put_photo
    method="POST")
  File "/app/share/eos-photos/src/share/facebook.py", line 265, in request
    files=files)
  File "/app/lib/python3.5/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/app/lib/python3.5/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/app/lib/python3.5/site-packages/requests/models.py", line 308, in prepare
    self.prepare_body(data, files, json)
  File "/app/lib/python3.5/site-packages/requests/models.py", line 496, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/app/lib/python3.5/site-packages/requests/models.py", line 159, in _encode_files
    fdata = fp.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
(I haven't isolated it 100%, but I think it's likely this comes from the switch to Python 3. I'm not sure if it's a bug in `requests` or not.)

**Comment by cosimoc** [comment]
@ptomato Thanks; other than the screenshot size warnings, I think I addressed all of your comments. I will try and upload new screenshots tomorrow though; while at it, I believe that it would be best to have them as part of the git repo itself.

**Comment by cosimoc** [comment]
@ptomato Screenshots added

**Pull request merged**
